# *****************************************************************************
# Copyright (c) 2025 ISE Group at Harbin Institute of Technology. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# *****************************************************************************

"""Math operations — NumPy-compatible interface on Ascend NPU.

Operator wrappers are auto-generated by _op_factory to eliminate boilerplate.
Special cases (signbit, modf, divmod, floor) retain hand-written corrections.
"""

import numpy as np

from ._core import math as _m
from ._op_factory import (
    wrap_binary,
    wrap_binary_auto_cast_no_dtype,
    wrap_binary_no_dtype,
    wrap_cumulative,
    wrap_reduction,
    wrap_unary,
    wrap_unary_dtype,
)
from .utils import _convert_dtype, ndarray

# ═══════════════════════════════════════════════════════════════════
# Trigonometric (auto-cast int/bool to float32 for CANN compat)
# ═══════════════════════════════════════════════════════════════════

sin = wrap_unary(_m.sin, auto_cast=True)
cos = wrap_unary(_m.cos, auto_cast=True)
tan = wrap_unary(_m.tan, auto_cast=True)
arcsin = wrap_unary(_m.arcsin, auto_cast=True)
arccos = wrap_unary(_m.arccos, auto_cast=True)
arctan = wrap_unary(_m.arctan, auto_cast=True)
arctan2 = wrap_binary_auto_cast_no_dtype(_m.arctan2)

radians = wrap_unary(_m.radians)
deg2rad = wrap_unary(_m.radians)
degrees = wrap_unary(_m.degrees)
rad2deg = wrap_unary(_m.rad2deg)
hypot = wrap_binary_no_dtype(_m.hypot)

# ═══════════════════════════════════════════════════════════════════
# Hyperbolic
# ═══════════════════════════════════════════════════════════════════

sinh = wrap_unary_dtype(_m.sinh)
cosh = wrap_unary_dtype(_m.cosh)
tanh = wrap_unary_dtype(_m.tanh)
arcsinh = wrap_unary_dtype(_m.arcsinh)
arccosh = wrap_unary_dtype(_m.arccosh)
arctanh = wrap_unary_dtype(_m.arctanh)

# ═══════════════════════════════════════════════════════════════════
# Arithmetic
# ═══════════════════════════════════════════════════════════════════

add = wrap_binary(_m.add)
subtract = wrap_binary(_m.subtract)
multiply = wrap_binary(_m.multiply)
divide = wrap_binary(_m.divide)
true_divide = wrap_binary(_m.true_divide)
floor_divide = wrap_binary(_m.floor_divide)
remainder = wrap_binary(_m.remainder)
mod = wrap_binary(_m.mod)
fmod = wrap_binary(_m.fmod)
power = wrap_binary(_m.power)
float_power = wrap_binary(_m.float_power)

reciprocal = wrap_unary_dtype(_m.reciprocal)
positive = wrap_unary_dtype(_m.positive)
negative = wrap_unary_dtype(_m.negative)


def modf(x):
    frac, inte = _m.modf(x)
    return [ndarray(frac), ndarray(inte)]


def divmod(x1, x2, dtype=None):
    res1, res2 = _m.divmod(x1, x2)
    _type = _convert_dtype(dtype)
    return [ndarray(res1, _type), ndarray(res2, _type)]


# ═══════════════════════════════════════════════════════════════════
# Exponents and logarithms
# ═══════════════════════════════════════════════════════════════════

exp = wrap_unary(_m.exp)
exp2 = wrap_unary(_m.exp2)
expm1 = wrap_unary(_m.expm1)
log = wrap_unary(_m.log)
log2 = wrap_unary(_m.log2)
log10 = wrap_unary(_m.log10)
log1p = wrap_unary(_m.log1p)
sqrt = wrap_unary(_m.sqrt)

logaddexp = wrap_binary_no_dtype(_m.logaddexp)
logaddexp2 = wrap_binary_no_dtype(_m.logaddexp2)

# ═══════════════════════════════════════════════════════════════════
# Miscellaneous
# ═══════════════════════════════════════════════════════════════════

absolute = wrap_unary(_m.absolute)
fabs = wrap_unary(_m.fabs)
sign = wrap_unary(_m.sign)
square = wrap_unary(_m.square)

relu = wrap_unary_dtype(_m.relu)
gelu = wrap_unary_dtype(_m.gelu)
sinc = wrap_unary_dtype(_m.sinc)

heaviside = wrap_binary_no_dtype(_m.heaviside)
copysign = wrap_binary_no_dtype(_m.copysign)
ldexp = wrap_binary_no_dtype(_m.ldexp)


def clip(a, a_min, a_max):
    return ndarray(_m.clip(a, a_min, a_max))


def nan_to_num(x, nan=0.0, posinf=None, neginf=None):
    return ndarray(_m.nan_to_num(x, nan, posinf, neginf))


# ═══════════════════════════════════════════════════════════════════
# Sums, products, differences
# ═══════════════════════════════════════════════════════════════════

sum = wrap_reduction(_m.sum, _m.sum, with_dtype=True)
prod = wrap_reduction(_m.prod, _m.prod, with_dtype=True)
nansum = wrap_reduction(_m.nansum, _m.nansum, with_dtype=True)
nanprod = wrap_reduction(_m.nanprod, _m.nanprod, with_dtype=True)

cumsum = wrap_cumulative(_m.cumsum)
cumprod = wrap_cumulative(_m.cumprod)
nancumsum = wrap_cumulative(_m.nancumsum)
nancumprod = wrap_cumulative(_m.nancumprod)


def cross(a, b, axis=None):
    return ndarray(_m.cross(a, b, axis))


# ═══════════════════════════════════════════════════════════════════
# Handling complex numbers
# ═══════════════════════════════════════════════════════════════════

real = wrap_unary(_m.real)

# ═══════════════════════════════════════════════════════════════════
# Floating point routines (signbit requires hand-written correction)
# ═══════════════════════════════════════════════════════════════════


def signbit(x):
    result = ndarray(_m.signbit(x))
    # CANN's aclnnSignbit does not handle IEEE 754 negative zero (-0.0).
    np_x = x.to_numpy()
    neg_zero_mask = np.signbit(np_x) & (np_x == 0)
    if neg_zero_mask.any():
        np_result = result.to_numpy().astype(np.bool_)
        np_result |= neg_zero_mask
        return ndarray(ndarray.from_numpy(np_result))
    return result


# ═══════════════════════════════════════════════════════════════════
# Rounding
# ═══════════════════════════════════════════════════════════════════

rint = wrap_unary_dtype(_m.rint)
ceil = wrap_unary_dtype(_m.ceil)
fix = wrap_unary_dtype(_m.fix)
trunc = wrap_unary_dtype(_m.trunc)


def around(x, decimals=0, dtype=None):
    return ndarray(_m.around(x, decimals, _convert_dtype(dtype)))


def round_(x, decimals=0, dtype=None):
    return ndarray(_m.round_(x, decimals, _convert_dtype(dtype)))


def floor(x, dtype=None):
    converted_dtype = _convert_dtype(dtype)
    if converted_dtype is None:
        host = x.to_numpy() if hasattr(x, "to_numpy") else np.asarray(x)
        if np.issubdtype(host.dtype, np.integer) or np.issubdtype(host.dtype, np.bool_):
            return ndarray.from_numpy(np.asarray(np.floor(host)))
    return ndarray(_m.floor(x, converted_dtype))


# ═══════════════════════════════════════════════════════════════════
# Extrema finding
# ═══════════════════════════════════════════════════════════════════

maximum = wrap_binary(_m.maximum)
minimum = wrap_binary(_m.minimum)
fmax = wrap_binary(_m.fmax)
fmin = wrap_binary(_m.fmin)

max = wrap_reduction(_m.max, _m.max, with_dtype=False)
min = wrap_reduction(_m.min, _m.min, with_dtype=False)
amax = wrap_reduction(_m.amax, _m.amax, with_dtype=False)
amin = wrap_reduction(_m.amin, _m.amin, with_dtype=False)
nanmax = wrap_reduction(_m.nanmax, _m.nanmax, with_dtype=False)

# ═══════════════════════════════════════════════════════════════════
# Rational routines
# ═══════════════════════════════════════════════════════════════════

gcd = wrap_binary(_m.gcd)
lcm = wrap_binary(_m.lcm)
