# *****************************************************************************
# Copyright (c) 2025 AISS Group at Harbin Institute of Technology. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# *****************************************************************************

from .array import (
    empty,
    empty_like,
    eye,
    full,
    full_like,
    identity,
    linspace,
    ones,
    ones_like,
    zeros,
    zeros_like
)

from .cann import (
    finalize,
    init,
    reset_device,
    reset_device_force,
    set_device
)

from . import linalg

from .linalg_ops import (
    dot,
    einsum,
    inner,
    matmul,
    outer,
    vdot
)

from .logic import (
    all,
    any,
    equal,
    greater,
    greater_equal,
    isfinite,
    isinf,
    isneginf,
    isposinf,
    less,
    less_equal,
    logical_and,
    logical_not,
    logical_or,
    logical_xor,
    not_equal
)

from .math import (
    absolute,
    add,
    amax,
    around,
    arccos,
    arccosh,
    arcsin,
    arcsinh,
    arctan,
    arctan2,
    arctanh,
    ceil,
    clip,
    copysign,
    cos,
    cosh,
    cross,
    cumprod,
    cumsum,
    deg2rad,
    degrees,
    divide,
    divmod,
    exp,
    exp2,
    expm1,
    fabs,
    fix,
    floor,
    floor_divide,
    fmax,
    fmin,
    fmod,
    float_power,
    gelu,
    gcd,
    heaviside,
    hypot,
    lcm,
    ldexp,
    log,
    log10,
    log1p,
    log2,
    logaddexp,
    logaddexp2,
    max,
    maximum,
    minimum,
    mod,
    modf,
    multiply,
    nan_to_num,
    nancumprod,
    nancumsum,
    nanmax,
    nanprod,
    nansum,
    negative,
    power,
    positive,
    prod,
    rad2deg,
    radians,
    real,
    reciprocal,
    relu,
    remainder,
    rint,
    round_,
    sign,
    signbit,
    sin,
    sinc,
    sinh,
    sqrt,
    square,
    subtract,
    sum,
    tan,
    tanh,
    true_divide,
    trunc
)

from .random import (
    binomial,
    exponential,
    geometric,
    gumbel,
    laplace,
    logistic,
    lognormal,
    normal,
    pareto,
    rayleigh,
    standard_cauchy,
    standard_normal,
    uniform,
    weibull
)

from .sorting import sort

from .utils import (
    broadcast_shape,
    ndarray
)


__all__ = [
    # .array
    "empty",
    "empty_like",
    "eye",
    "full",
    "full_like",
    "identity",
    "linspace",
    "ones",
    "ones_like",
    "zeros",
    "zeros_like",
    # .cann
    "finalize",
    "init",
    "reset_device",
    "reset_device_force",
    "set_device",
    # .linalg
    "linalg",
    # .linalg_ops
    "dot",
    "einsum",
    "inner",
    "matmul",
    "outer",
    "vdot",
    # .logic
    "all",
    "any",
    "equal",
    "greater",
    "greater_equal",
    "isfinite",
    "isinf",
    "isneginf",
    "isposinf",
    "less",
    "less_equal",
    "logical_and",
    "logical_not",
    "logical_or",
    "logical_xor",
    "not_equal",
    # .math
    "absolute",
    "add",
    "amax",
    "around",
    "arccos",
    "arccosh",
    "arcsin",
    "arcsinh",
    "arctan",
    "arctan2",
    "arctanh",
    "ceil",
    "clip",
    "copysign",
    "cos",
    "cosh",
    "cross",
    "cumprod",
    "cumsum",
    "deg2rad",
    "degrees",
    "divide",
    "divmod",
    "exp",
    "exp2",
    "expm1",
    "fabs",
    "fix",
    "floor",
    "floor_divide",
    "fmax",
    "fmin",
    "fmod",
    "float_power",
    "gelu",
    "gcd",
    "heaviside",
    "hypot",
    "lcm",
    "ldexp",
    "log",
    "log10",
    "log1p",
    "log2",
    "logaddexp",
    "logaddexp2",
    "max",
    "maximum",
    "minimum",
    "mod",
    "modf",
    "multiply",
    "nan_to_num",
    "nancumprod",
    "nancumsum",
    "nanmax",
    "nanprod",
    "nansum",
    "negative",
    "power",
    "positive",
    "prod",
    "rad2deg",
    "radians",
    "real",
    "reciprocal",
    "relu",
    "remainder",
    "rint",
    "round_",
    "sign",
    "signbit",
    "sin",
    "sinc",
    "sinh",
    "sqrt",
    "square",
    "subtract",
    "sum",
    "tan",
    "tanh",
    "true_divide",
    "trunc",
    # .random
    "binomial",
    "exponential",
    "geometric",
    "gumbel",
    "laplace",
    "logistic",
    "lognormal",
    "normal",
    "pareto",
    "rayleigh",
    "standard_cauchy",
    "standard_normal",
    "uniform",
    "weibull",
    # .sorting
    "sort",
    # .utils
    "broadcast_shape",
    "ndarray"
]
